### ISSUE TITLE
linux-aarch64-lts and linux-aarch64 are in conflict

### ISSUE THREAD

**Issue by pbtrung** [lynix/linux-aarch64-lts#2]
Like Arch, `linux-aarch64` and `linux-aarch64-lts` should not be in conflict.
For example, right now my ARM server is running well with `linux-aarch64`. When I tried to install `linux-aarch64-lts`, it requires to remove `linux-aarch64`. Scary!! It could break my system if anything goes wrong, so I think it's best to let users decide whether or not to remove `linux-aarch64` **after** installing and **sucessfully** booting into `linux-aarch64-lts`.

**Comment by lynix** [comment]
The conflict with the regular kernel package is stated explicitly in the `PKGBUILD`. This is done intentionally, so nothing I'd consider 'scary'. Take a look at [linux-aarch64-rc](https://github.com/archlinuxarm/PKGBUILDs/blob/b1b6b08fcf9938409b535590bbd703d47b5598e8/core/linux-aarch64-rc/PKGBUILD#L76C12-L76C12), this package also conflicts with the default kernel package.

I agree with your point that it would be nice to have the -lts kernel alongside with the regular one to allow dual-booting. However, this package also targets SBCs where we often have simple boot loaders that do not offer interactive kernel selection, so we need to rely on a predefined kernel image (and initrd) name.

I have chosen to offer a drop-in replacement for the regular kernel package so that SBC users do not need to manually reconfigure their boot loaders for it to work.

I might reconsider this decision at some point, currently I see more benefit from the drop-in variant. I'll have a look to see if there are additional difficulties (e.g. files that would conflict between the two kernel packages) or if it's just my use case assumption that prevents us from having both kernels installed at the same time.

**Comment by lynix** [comment]
I have had a look at the package contents.

In addition to what I have said above there is another point of conflict: both kernel packages would ship DTBs (Device Tree Blobs, .dtb files) in `/boot/dtbs`. This path is common practice and changing it to something else for the -lts package (e.g. `/boot/dtbs-lts`) would again require manual configuration changes for the boot loader.

I will close this one for now as I don't see an elegant solution to this problem. Please feel free to re-open if you have suggestions on how to achieve a painless transition for SBC users.
