### ISSUE TITLE
Oh dear, /boot/Image is missing

### ISSUE THREAD

**Issue by ambiamber** [lynix/linux-aarch64-lts#4]
Hello to you,

I finally got around to installing your linux-aarch64-lts on my Globalscale Mochabin.  My firmware is configure to boot off of boot/Image and in the past my linux packages and IIRC yours too, were configure to install /boot/Image.

The screenshot shows it had a bad day without its beloved Image file.

![2023-11-26 bad magic](https://github.com/lynix/linux-aarch64-lts/assets/80137437/c0d9cb58-af33-49c3-83da-7c00fb13e9ca)

Not to worry, I just made a symlink and everything is peachy now.
```
lrwxrwxrwx 1 root root 25 Nov 26 11:43 /boot/Image -> vmlinuz-linux-aarch64-lts
```
You might want to consider adjusting your package to include making such a symlink.

Other than that, I'm utterly delighted with your excellent work!

**Comment by lynix** [comment]
Hi and thanks for your kind words! :)

You should have been presented with a warning that the kernel image name has changed, implemented in ae0adef7, that looks like this:

```
Please note that the kernel binary and initrd names have changed from

    /boot/Image
    /boot/initramfs-linux.img

to

    /boot/vmlinuz-linux-aarch64-lts
    /boot/initramfs-linux-aarch64-lts.img

in order to match the naming scheme supported by Arch Linux standard
tooling.

This change will likely require you to update your booloader
configuration accordingly.
```

Background info:

In 82594e0a I have adopted the behaviour of all official Arch Linux (not Arch Linux ARM) kernel packages, i.e. to install the kernel image in /lib/modules. They do this since Nov 2019 (see [News Article](https://archlinux.org/news/new-kernel-packages-and-mkinitcpio-hooks/)), I guess ALARM is lacking far behind.

From there the kernel image is automatically copied to /boot by `mkinitcpio` using a configured name. Unfortunately this name is kernel-agnostic so I simply couldn't use a generic "/Image" here. I'm sorry for the inconvenience that I have caused with this change but I try to stay as close to the official kernel packages as possible.

This new approach also has the benefit that you could have different kernel images installed in parallel (although on ARM they currently still conflict on their DTB directory, this is an issue that's still on my list).

**Comment by ambiamber** [comment]
Thank you for the explanation. Just one question, is there any reason that this symlink would not fit into your scheme of things?
```
lrwxrwxrwx 1 root root 25 Nov 26 11:43 /boot/Image -> vmlinuz-linux-aarch64-lts
```

**Comment by lynix** [comment]
> Just one question, is there any reason that this symlink would not fit into your scheme of things?

That symlink would prevent you from having two different kernel packages installed at the same time (as they would both want to have it), e.g. an LTS kernel and a non-LTS one (like with Arch Linux).

I know this is currently not possible anyway due to conflicting DTB directories, but as I said above, I'd like to make this possible in the future and rather not make steps backwards.

**Comment by ambiamber** [comment]
The reason that I'm asking is that I have two "disks", each with a different distro.  One of the distros uses `/boot/Image`.

**Comment by ambiamber** [comment]
Oh, I just thought of something. Can the DTB directories for each kernel be switched between by way of using a symlink?

**Comment by ambiamber** [comment]
Never mind, I'll just deal with it.

**Comment by lynix** [comment]
Just a thought regarding symlinks on /boot in general: it's quite common on some platforms (think of EFI systems) that /boot is a FAT32 partition. So unfortunately no symlinks there ;)
